### ISSUE TITLE
Email Verification

### ISSUE THREAD

**Issue by kavitharaju** [friendsofagape/autographa-mt#1]
While doing a sign up the verification link send to the emial is not working.

it says
`https://None/v1/verifications/21b14e2fdd8e4ce895558be4ccaa44e4`..... but when I copy the link location or click on it, it is another link `http://bjdaicf.r.bh.d.sendibt3.com/tr/cl/JioabZ....`

And the page is not loading.

**Comment by bijob89** [comment]
The url issue has been resolved and the code has been updated. The reason why `None` appeared on the url was because the environment variable which stores the `base url` was empty.
