### ISSUE TITLE
Change Names in the dashboard 

### ISSUE THREAD

**Issue by Joel-C-Johnson** [friendsofagape/autographa-mt#101]
Need to change 
1. Create Organisation to Request Admin Permission
2. Verify User to Change User Roles
3. Change Verify Organisation to Admin Requests

**Comment by jincypjose** [comment]
This issue has been closed
1. Create Organisation to Request Admin Permission
2. Verify User to Change User Roles
3. Change Verify Organisation to Verify Admin Request
