### ISSUE TITLE
Need to Modify User List page

### ISSUE THREAD

**Issue by Joel-C-Johnson** [friendsofagape/autographa-mt#104]
-change the table styles
-removed the sorting functionality from all the columns except admins column
-remove the super admin users from the list 
-change the "user list" name to "change user roles"

**Comment by jincypjose** [comment]
This issue has been closed.
-changed the table styles
-removed the sorting functionality from all the columns except admins column
-removed the super admin users from the list 
-changed the "user list" name to "change user roles"
