### ISSUE TITLE
The token translated online doesnot get downloaded ofline

### ISSUE THREAD

**Issue by jincypjose** [friendsofagape/autographa-mt#123]
After translating online the tokens doesnot get downloaded in excel (for translator and admin role)

**Comment by AnnCherianA** [comment]
Verified that the tokens translated online are displaying on downloading the tokens offline
![Online token translation](https://user-images.githubusercontent.com/74647279/106795132-b7796c80-667f-11eb-9733-61f7af11d4a6.jpg)
![Online translated token displays when downloaded offline](https://user-images.githubusercontent.com/74647279/106795203-cb24d300-667f-11eb-9135-bd2d19bed6dc.jpg)
