### ISSUE TITLE
Use Auto Complete Select for loading target languages

### ISSUE THREAD

**Issue by Joel-C-Johnson** [friendsofagape/autographa-mt#13]
## User Story
The browser gets slower while loading target language in New source tab

## Acceptance Criteria
Need to change the select npm to react-virtualized-select

## Definition of Done
The target language data should load fast..

## ScreenShot
![Screenshot from 2019-08-06 11-40-00.png](https://images.zenhubusercontent.com/58f4700f51aa2c30577b7ae2/18af6cf0-f1d5-4b8f-b976-34bc85d700ec)

**Comment by bijob89** [comment]
Auto Complete feature added to UI
