### ISSUE TITLE
Token count does not increase on saving a translated token

### ISSUE THREAD

**Issue by AnnCherianA** [friendsofagape/autographa-mt#136]
Issue Description : In the translation  token progress bar the token count does not increase on saving a translated token.
Steps:
Login as translator

Select My Projects
Select a project and click on Open Project
Select a Book . Eg Jon
From the token pane, select a token
Update the token translation pane
Click Save
Observation: A message saying Translated token inserted is shown
However, the translated token progress bar does not increment the count of the token
Case 1: For an untranslated token, after translation, the count should increment
Case 2:For a translated token, the count should not increment after saving

Expected Result:
Along with saving the translated word, the count of the translated token(if previously untranslated ) should work.
![Translation token count not increasing](https://user-images.githubusercontent.com/74647279/110471515-39870600-8102-11eb-8afa-4643b5e94721.jpg)

**Comment by Joel-C-Johnson** [comment]
We had already an option that allows the progress bar to update whenever a token is translated online(translated/untranslated). But the app gets very slow when each time it's calling the API's.  Now we have changed that workflow and given an option to refresh the translation progress by clicking the reload button near the progress bar.
