### ISSUE TITLE
Not Able to Select books in My project option 

### ISSUE THREAD

**Issue by Savithamark** [friendsofagape/autographa-mt#21]
When we log in as organization admin, We are not able to select books in My project option

![image.png](https://images.zenhubusercontent.com/5d2eb94bc7368a420fad5c8f/e118201b-4f26-4227-917a-5d53f48465ab)

**Comment by bijob89** [comment]
This happens when no book is assigned under a project. The work around would be to provide a pop up message stating that no books are available
