### ISSUE TITLE
Organization Admin is able to view organisation list

### ISSUE THREAD

**Issue by Savithamark** [friendsofagape/autographa-mt#24]
Only Super admin has the access to view organization list from UI, but while doing the API testing organization admin is also able to access organization list

**Comment by bijob89** [comment]
Organisation admin will be able to view the organisation which he/she is a part of

**Comment by Joel-C-Johnson** [comment]
as a super admin, he can able to view all the organisation list, but for admin, he can only view the organisation which he is part of (he can able to see onlt his organisation)
