### ISSUE TITLE
Delete and Activate functionalities

### ISSUE THREAD

**Issue by kavitharaju** [friendsofagape/autographa-mt#34]
Add UI functionality for admin to delete and activate projects. And for super admin to delete and activate users, projects, orgs, and sources

**Comment by bijob89** [comment]
@kavitharaju , this also needs to be handled at the API level. The db needs an IsActive field and the same needs to be returned via API.

**Comment by kavitharaju** [comment]
please check the current get API methods that includes the status info also
We have also added separate delete APIs that sets the status as False. So I hope it is handled at API side. Please check and revert if it needs some changes

**Comment by bijob89** [comment]
We could remove the delete name from the end-point. Instead we can change the methods from `GET` to `DELETE`

**Comment by bijob89** [comment]
So for deleting use a `DELETE` method and can pass the Id as query parameter. For ex `/v1/autographamt/users/:id`. Use a `PUT` for updates.
