### ISSUE TITLE
Error while trying to create organisation

### ISSUE THREAD

**Issue by kavitharaju** [friendsofagape/autographa-mt#35]
The Operation Agape technical support faced an issue while creating the organization in the app. Following is the details provided

![image.png](https://images.zenhubusercontent.com/5b35d9b9cc64017c8eee3cdb/91b77404-de7a-4527-8739-c3cb361257c4)

![image.png](https://images.zenhubusercontent.com/5b35d9b9cc64017c8eee3cdb/37142b9f-772d-4adc-819e-9b5d72d8587a)

![image.png](https://images.zenhubusercontent.com/5b35d9b9cc64017c8eee3cdb/2ab1b0bd-6254-42d4-840c-3a1645a3bbdd)

![image.png](https://images.zenhubusercontent.com/5b35d9b9cc64017c8eee3cdb/bd458b21-ccd5-481e-8860-e7d4b834ec15)

![image.png](https://images.zenhubusercontent.com/5b35d9b9cc64017c8eee3cdb/e619087a-010c-4d77-b2bf-e2001a4b9e04)

![image.png](https://images.zenhubusercontent.com/5b35d9b9cc64017c8eee3cdb/33efa8c6-4d3a-4500-8ae2-d5da1dc66aa3)

**Comment by udkumar** [comment]
@kavitharaju 
I have tested and reproduced the issue:
I was getting the issue with creating an organization because of the **phone** data type and I did changes accordingly.
I have tested on autographMT production.
