### ISSUE TITLE
Projects with new target languages

### ISSUE THREAD

**Issue by kavitharaju** [friendsofagape/autographa-mt#38]
Currently target language can only be selected from a given list. As the minority languages we are working on does not occur in the list there should be provision to enter their name manually

**Comment by bijob89** [comment]
@kavitharaju , What would be the convention of storing this information to the DB.

**Comment by kavitharaju** [comment]
I would suggest we add new entires to the **languages** table, with auto increment language ids and 4 letter code using the first 4 letters(to avoid repeating the existing 3 letter codes), and check if code is existing before addition

**Comment by Joel-C-Johnson** [comment]
Currently, we have updated the language list with all the available languages (includes minority languages)
