### ISSUE TITLE
Enable token download and upload via excel

### ISSUE THREAD

**Issue by kavitharaju** [friendsofagape/autographa-mt#40]
The tokens are to be downloaded in an excel in three columns(token_id, token, translations).

It should be possible to down load tokens, book wise or as the whole Bible(for all available books in DB) in one sheet. And if there are token translations available for some tokens, that should be provided on the "translations" column at the time of download.

The token upload function should be able to accept the filled excel, do necessary cheack and update all the tokens in the DB as per the uploaded values for that corresponding project.

If any new API is required for this request can be raised in the respective repo.

**Comment by Joel-C-Johnson** [comment]
We are downloading the tokens in an excel in three column Token, Translation and senses ( token id is not provided as the value will be a random number)
Then tokens are displayed and download as bookwise and if the translation is available in DB that should be provided on the "translations" column at the time of download.
Provided an upload functionality which can upload the tokens from an excel file
