### ISSUE TITLE
Not going directly to the homepage after login

### ISSUE THREAD

**Issue by Joel-C-Johnson** [friendsofagape/autographa-mt#6]
## User Story

After login, the UI is not redirecting to the homepage. It's displaying an empty page. Need to manually refresh the browser for going the homepage.
## Acceptance Criteria
Need to check with the react-router
## Definition of Done
The UI must go directly to the homepage after login![Screenshot from 2019-08-02 14-33-42.png](https://images.zenhubusercontent.com/58f4700f51aa2c30577b7ae2/794738bc-ef64-4ed6-889e-d5071a02f442).

**Comment by kavitharaju** [comment]
After login sometimes an error page is being displayed and the homepage will be loaded only after a refresh(F5)
