### ISSUE TITLE
Notifications for the new project assigned

### ISSUE THREAD

**Issue by jincypjose** [friendsofagape/autographa-mt#66]
Pop up like feature in projects list page. so, that users will get notified for the new Project assigned (in three of the user roles)

**Comment by Joel-C-Johnson** [comment]
The issue has been solved by sending an email (notification mail ) to the user if there is any project assigned

**Comment by Joel-C-Johnson** [comment]
tested the function in staging and working as expected

**Comment by Joel-C-Johnson** [comment]
there is another issue opened related to this issue. When an admin assign a book to a user for a project the user will get notification mail
