### ISSUE TITLE
Unable to upload token translation

### ISSUE THREAD

**Issue by Joel-C-Johnson** [friendsofagape/autographa-mt#7]
## User Story
Not able to upload the token translation. message: "Server Error" 
## Acceptance Criteria
Need to check the API
## Definition of Done
The UI must able to upload the token translation.

##[Uploading... Screenshot from 2019-08-02 14-43-46.png ] Screenshot

**Comment by Joel-C-Johnson** [comment]
![Screenshot from 2019-08-02 14-43-46](https://user-images.githubusercontent.com/25791348/62359325-34c89c00-b534-11e9-8018-263837b53403.png)

**Comment by bijob89** [comment]
Token update error resolved and updated code has been pushed
