### ISSUE TITLE
New Source uploading error

### ISSUE THREAD

**Issue by Joel-C-Johnson** [friendsofagape/autographa-mt#8]
## User Story
Cant able to create New Source

## Acceptance Criteria
Needs to be tested with API and D![Screenshot from 2019-08-02 14-54-29.png]

## Definition of Done
Must able to create new Sources
## Screenshot
(https://images.zenhubusercontent.com/58f4700f51aa2c30577b7ae2/83780d5e-0b99-4d90-b885-f218a2355b3e)B.

**Comment by bijob89** [comment]
Corrected the error in API code which didn't allow creating sources.
