### ISSUE TITLE
There is no mehod to find translated and non transalted tokens

### ISSUE THREAD

**Issue by Joel-C-Johnson** [friendsofagape/autographa-mt#82]
There are no identifications for translated and untranslated tokens in both online and offline.

Solutions:  Given a checkbox which can get only the untranslated tokens 
Suggestion:
1. Also the progress bar gives an indication of the status of translation

**Comment by jincypjose** [comment]
This issue has been closed.
Given a checkbox which can get only the untranslated tokens, Also the progress bar gives an indication of the status of translation
