### ISSUE TITLE
Sort books 

### ISSUE THREAD

**Issue by Joel-C-Johnson** [friendsofagape/autographa-mt#91]
Sort the books in bible order 
It will be good to sort in  OT and NT  order

**Comment by jincypjose** [comment]
LIST OF UI PAGES WHERE BOOKS IN THE BIBLE NEED TO BE SORTED
 - Source Languages (While clicking the VIEW button)
 - Statistics Page (While clicking the BOOKS button)
 - My Projects (While clicking the button in Books Assigned column)
 - Translation Page (While clicking the Select Book button)

**Comment by Joel-C-Johnson** [comment]
can u specify the user roles ( eg admin / user / superAdmin)

**Comment by jincypjose** [comment]
This issue has been closed. Sorted books in all the above mentioned pages
