### ISSUE TITLE
Change bible name ( from 3 letter code to full names)

### ISSUE THREAD

**Issue by Joel-C-Johnson** [friendsofagape/autographa-mt#97]
Need to change the 3 letter bible code to full bible names with upperCase ( all the UI pages where bible books list shows)

**Comment by Joel-C-Johnson** [comment]
Below button which is not able to display full book names because of the API data
1. "Select book" in Translation page
2. "View" button in Available Source page
3. "Books"  button in Assign project page

**Comment by jincypjose** [comment]
This issue has been closed.The 3 Letter code book names has been changed to full names except the button which is not able to display full book names because of the API data
1. "Select book" in Translation page
2. "View" button in Available Source page
3. "Books" button in Assign project page
